### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by atamazian** [tubo213/kaggle-child-mind-institute-detect-sleep-states#38]
Can you add a license to this repository?

**Comment by tubo213** [comment]
MIT license has been set up.

**Comment by tubo213** [comment]
@atamazian 

Please comment on [Disscussion](https://www.kaggle.com/competitions/child-mind-institute-detect-sleep-states/discussion/452940#2530545) for a summary, as exchanges on github may fall under the category of private sharing.

**Comment by atamazian** [comment]
Done
