### ISSUE TITLE
Cannot run run/prepare_data.py

### ISSUE THREAD

**Issue by riow1983** [tubo213/kaggle-child-mind-institute-detect-sleep-states#39]
When I ran the following command, I've got the error message:
```bash
$ rye run python -m run/prepare_data.py phase=train,test
```
/home/jovyan/workspace/kaggle-child-mind-institute-detect-sleep-states/.venv/bin/python: Error while finding module specification for 'run/prepare_data.py' (ModuleNotFoundError: No module named 'run/prepare_data'). Try using 'run/prepare_data' instead of 'run/prepare_data.py' as the module name.

```bash
$ rye run python -m run/prepare_data phase=train,test
```
/home/jovyan/workspace/kaggle-child-mind-institute-detect-sleep-states/.venv/bin/python: No module named run/prepare_data
***
How can I work around this?

**Comment by welshonionman** [comment]
Try this.
`rye run python run/prepare_data.py -m phase=train,test`

**Comment by tubo213** [comment]
@riow1983 
I had the wrong code, @welshonionman  comment is correct.

Corrected.
https://github.com/tubo213/kaggle-child-mind-institute-detect-sleep-states/pull/40

**Comment by riow1983** [comment]
@welshonionman @tubo213 Thanks! It seems to work. I encountered a killing operation before finishing the task. Will raise another issue since it must be another issue.

**Comment by tubo213** [comment]
@riow1983 

Please comment on [Disscussion](https://www.kaggle.com/competitions/child-mind-institute-detect-sleep-states/discussion/452940#2530545) for a summary, as exchanges on github may fall under the category of private sharing.

**Comment by riow1983** [comment]
@tubo213 
Thanks. Done: https://www.kaggle.com/competitions/child-mind-institute-detect-sleep-states/discussion/452940#2531150
