### ISSUE TITLE
Running run/prepare_data.py killed

### ISSUE THREAD

**Issue by riow1983** [tubo213/kaggle-child-mind-institute-detect-sleep-states#45]
It must not be an issue but is a question.
I encountered an intermediate killing operation before finishing the task:
```
$ rye run python run/prepare_data.py -m phase=train,test
```
[2023-11-12 23:53:26,135][HYDRA] Launching 2 jobs locally
[2023-11-12 23:53:26,135][HYDRA]        #0 : phase=train
Killed
***
No other error messages appeared.
It might be my environmental issue. But do we have a minimum requirement for e.g., RAM of an environment that runs this command?
FYI: the spec of my environment:
g4dn.xlarge (AWS instance) - 4 cores - 16 GB RAM - 1 GPU - 40Gi Disk

**Comment by tubo213** [comment]
@riow1983 

I think it is due to lack of RAM.
Try running with a large amount of RAM (about 32 GB)

**Comment by riow1983** [comment]
Thanks! Will do.

**Comment by tubo213** [comment]
@riow1983 

Please comment on Disscussion for a summary, as exchanges on github may fall under the category of private sharing.

**Comment by riow1983** [comment]
@tubo213 
Thanks. Done: https://www.kaggle.com/competitions/child-mind-institute-detect-sleep-states/discussion/452940#2531150
