### ISSUE TITLE
Plz~, May I ask you the version of Transformer

### ISSUE THREAD

**Issue by Zero-coder** [tubo213/kaggle-child-mind-institute-detect-sleep-states#60]
defaults:
  - _self_
  - dir: local
  - model: TransformerAutoModel #

**Comment by tubo213** [comment]
What is your question?

**Comment by Zero-coder** [comment]
![image](https://github.com/tubo213/kaggle-child-mind-institute-detect-sleep-states/assets/54145971/5871fae8-bed6-4f7a-84a6-818b52d9b536)
what the actual operation in the code about ` don't use feature_extractor and decoder.`

**Comment by tubo213** [comment]
@Zero-coder 

> hello, may I ask What's the version of transformer?

I use version 4.33.3

> what the actual operation in the code about  don't use feature_extractor and decoder.

TransformerAutoModel does not use feature_extractor, decoder.

It takes wave as input and outputs predictions.

**Comment by Zero-coder** [comment]
Oh, I see, thank you very much ~ have a good day.🌟🌟🌟
