### ISSUE TITLE
Abount Implementation of CutMix for 1D signals

### ISSUE THREAD

**Issue by bilzard** [tubo213/kaggle-child-mind-institute-detect-sleep-states#62]
Hi. Thanks for sharing great code.
I have a discussion for cutmix of 1D inputs.

In my understanding, taking square root is necessary only for 2D inputs, because in 2D image, `lambda` means cut-out rate of area.
So, if it is applied to 1D signals, I think square root is not necessary because `lambda` means cut-out rate of frame length.

```python
def get_rand_1dbbox(n_timesteps: int, lam: float) -> tuple[int, int]:
    """Get random 1D bounding box.

    Args:
        n_timesteps (int): Number of timesteps.
        lam (float): Lambda value.

    Returns:
        tuple[int, int]: (start, end) of the bounding box.
    """
    cut_rat = np.sqrt(1.0 - lam)
    cut_len = int(n_timesteps * cut_rat)

    start = np.random.randint(0, n_timesteps - cut_len)
    end = start + cut_len

    return start, end
```

Thus, fixing as below looks more natural to me.

```python
def get_rand_1dbbox(n_timesteps: int, lam: float) -> tuple[int, int]:
    """Get random 1D bounding box.

    Args:
        n_timesteps (int): Number of timesteps.
        lam (float): Lambda value.

    Returns:
        tuple[int, int]: (start, end) of the bounding box.
    """
    cut_rat = 1.0 - lam
    cut_len = int(n_timesteps * cut_rat)

    start = np.random.randint(0, n_timesteps - cut_len)
    end = start + cut_len

    return start, end
```

https://github.com/tubo213/kaggle-child-mind-institute-detect-sleep-states/blob/main/src/augmentation/cutmix.py#L15

**Comment by yukiu00** [comment]
@bilzard 

As you pointed out, np.sqrt was not needed.

Thanks for spotting the mistake.
I have corrected the code.

https://github.com/tubo213/kaggle-child-mind-institute-detect-sleep-states/pull/63
